#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."

# Mark the necessary Go modules as private to avoid Go's proxy
export GOPRIVATE="${GOPRIVATE:+$GOPRIVATE,}github.com/bruce-hill/bruce-test-api-go/v2,github.com/stainless-sdks/bruce-test-api-go/v2"

REPLACEMENT="${1:-"../bruce-test-api-go"}"
echo "==> Replacing Go SDK with $REPLACEMENT"
go mod edit -replace github.com/bruce-hill/bruce-test-api-go/v2="$REPLACEMENT"
go mod tidy -e
